service: lambda-particle-trigger

provider:
  region: eu-west-2
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 5
  tracing: true
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"
  stage: ${opt:stage, 'staging'}
  environment:
    CONFIG: ${file(./config.json.config)}

functions:
  set:
    handler: src/index.set
    events:
      - schedule:
          rate: cron(0 15 * * ? *)
          input:
            data: 1
      - schedule:
          rate: cron(30 20 * * ? *)
          input:
            data: 0
toggle:
    handler: src/index.toggle
    events:
      - iot:
          sql: "SELECT * FROM 'iotbutton/${self:custom.iotThingDSN}'"

resources:
  Resources:
    IoTThing:
      Type: AWS::IoT::Thing
      Properties:
        ThingName:
          Fn::Join:
            - ''
            - - iotbutton_
              - ${self:custom.iotThingDSN}

    IoTPolicy:
      Type: AWS::IoT::Policy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Action: iot:Publish
            Effect: Allow
            Resource:
              Fn::Join:
                - ''
                - - 'arn:aws:iot:'
                  - Ref: AWS::Region
                  - ":"
                  - Ref: AWS::AccountId
                  - ":topic/iotbutton/"
                  - ${self:custom.iotThingDSN}

    IoTPolicyPrincipalAttachment:
      Type: AWS::IoT::PolicyPrincipalAttachment
      Properties:
        PolicyName:
          Ref: IoTPolicy
        Principal: ${self:custom.iotThingCertARN}

    IoTThingPrincipalAttachment:
      Type: AWS::IoT::ThingPrincipalAttachment
      Properties:
        Principal: ${self:custom.iotThingCertARN}
        ThingName:
          Ref: IoTThing

    iotHouse:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: iot_house
        AttributeDefinitions:
          - AttributeName: button
            AttributeType: S
        KeySchema:
          - AttributeName: button
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

plugins:
  - serverless-webpack
  - serverless-dynamodb-local
  - serverless-offline

  webpack:
    includeModules:
      forceExclude:
        - aws-sdk

  serverless-offline:
    port: 4000
